import js from "@eslint/js";
import importPlugin from "eslint-plugin-import";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
	js.configs.recommended,
	...tseslint.configs.recommended,
	{
		ignores: [
			"**/node_modules/**",
			"**/build/**",
			"**/dist/**",
			"**/tmp/**",
			"**/generated/**",
			"**/.react-router/**",
			"**/scripts/**",
			"**/*.config.js",
			"**/*.config.cjs",
			"**/*.config.mjs",
		],
	},
	{
		files: ["**/*.{js,jsx,ts,tsx}"],
		languageOptions: {
			parser: tseslint.parser,
			parserOptions: {
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: true,
				},
			},
			globals: {
				console: "readonly",
				process: "readonly",
				Buffer: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
				global: "readonly",
				NodeJS: "readonly",
				window: "readonly",
				document: "readonly",
				navigator: "readonly",
				fetch: "readonly",
				URL: "readonly",
				URLSearchParams: "readonly",
				FormData: "readonly",
				Headers: "readonly",
				Request: "readonly",
				Response: "readonly",
				setTimeout: "readonly",
				clearTimeout: "readonly",
				setInterval: "readonly",
				clearInterval: "readonly",
			},
		},
		rules: {
			"@typescript-eslint/no-unused-vars": [
				"error",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
					caughtErrorsIgnorePattern: "^_",
				},
			],
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/explicit-module-boundary-types": "off",
			"@typescript-eslint/no-non-null-assertion": "warn",
			"@typescript-eslint/ban-ts-comment": [
				"warn",
				{
					"ts-ignore": "allow-with-description",
					"ts-expect-error": "allow-with-description",
					"ts-nocheck": true,
					"ts-check": false,
				},
			],
			"no-var": "off",
			"prefer-const": "off",
			"no-debugger": "error",
			"no-alert": "error",
			"no-unused-vars": "off",
			"no-undef": "off",
			"no-warning-comments": [
				"warn",
				{
					terms: ["TODO", "FIXME", "HACK", "XXX"],
					location: "start",
				},
			],
			indent: "off",
			quotes: "off",
			semi: "off",
			"comma-dangle": "off",
			"arrow-parens": "off",
			"object-curly-spacing": "off",
			"array-bracket-spacing": "off",
			"space-before-function-paren": "off",
			"keyword-spacing": "off",
			"space-infix-ops": "off",
			"eol-last": "off",
			"linebreak-style": "off",
			"no-multiple-empty-lines": "off",
			"no-trailing-spaces": "off",
			"padded-blocks": "off",
		},
	},
	{
		files: ["**/*.{js,jsx,ts,tsx}"],
		rules: {
			"no-console": "error",
		},
	},
	{
		files: ["**/*.{js,jsx,ts,tsx}"],
		plugins: {
			import: importPlugin,
		},
		rules: {
			"import/order": "off",
			"import/no-duplicates": "off",
			"import/no-unresolved": "off",
			"import/named": "off",
		},
	},
	{
		files: ["**/*.{jsx,tsx}"],
		plugins: {
			react: reactPlugin,
			"react-hooks": reactHooksPlugin,
		},
		settings: {
			react: {
				version: "detect",
			},
		},
		rules: {
			"react/jsx-uses-react": "error",
			"react/jsx-uses-vars": "error",
			"react/prop-types": "off",
			"react/react-in-jsx-scope": "off",
			"react/display-name": "off",
			"react/jsx-key": "error",
			"react/jsx-no-duplicate-props": "error",
			"react/jsx-no-undef": "error",
			"react/no-children-prop": "error",
			"react/no-danger-with-children": "error",
			"react/no-deprecated": "error",
			"react/no-direct-mutation-state": "error",
			"react/no-find-dom-node": "error",
			"react/no-is-mounted": "error",
			"react/no-render-return-value": "error",
			"react/no-string-refs": "error",
			"react/no-unescaped-entities": "error",
			"react/no-unknown-property": "error",
			"react/no-unsafe": "off",
			"react/require-render-return": "error",
			"react/self-closing-comp": "off",
			"react/jsx-closing-bracket-location": "off",
			"react/jsx-closing-tag-location": "off",
			"react/jsx-curly-spacing": "off",
			"react/jsx-equals-spacing": "off",
			"react/jsx-first-prop-new-line": "off",
			"react/jsx-indent": "off",
			"react/jsx-indent-props": "off",
			"react/jsx-max-props-per-line": "off",
			"react/jsx-tag-spacing": "off",
			"react/jsx-wrap-multilines": "off",
			"react-hooks/rules-of-hooks": "error",
			"react-hooks/exhaustive-deps": "warn",
		},
	},
	{
		files: ["**/*.test.{js,jsx,ts,tsx}", "**/*.spec.{js,jsx,ts,tsx}"],
		languageOptions: {
			globals: {
				jest: "readonly",
				test: "readonly",
				expect: "readonly",
				describe: "readonly",
				beforeEach: "readonly",
				afterEach: "readonly",
				beforeAll: "readonly",
				afterAll: "readonly",
				it: "readonly",
			},
		},
		rules: {
			"no-console": "off",
			"@typescript-eslint/no-explicit-any": "off",
		},
	},
);
