// Sensor Health & Data Quality Types
export type HealthStatus = "healthy" | "stale" | "silent";
export type DataQualityStatus = "good" | "missing" | "inconsistent";
export type IngestionSource = "api" | "csv";
export type IngestionStatus = "ok" | "api_error" | "csv_error";
export type QualityWindow = "1h" | "24h" | "7d";
export type ErrorSeverity = "warning" | "alert";

export interface SensorHealthRecord {
	sensorId: string;
	lastReportedAt: string;
	expectedIntervalSeconds: number;
	warningThresholdSeconds: number;
	criticalThresholdSeconds: number;
	healthStatus: HealthStatus;
}

export interface DataQualityRecord {
	sensorId: string;
	window: QualityWindow;
	expectedPoints: number;
	receivedPoints: number;
	missingPoints: number;
	inconsistentPoints: number;
	completenessPct: number;
	consistencyPct: number;
	freshnessPct: number;
	qualityStatus: DataQualityStatus;
	notes?: string;
}

export interface IngestionError {
	id: string;
	sensorId: string;
	timestamp: string;
	source: IngestionSource;
	errorCode: string;
	message: string;
	severity: ErrorSeverity;
}

// Sensor Health Records - 40 sensors matching sensors.ts
export const sensorHealthRecords: SensorHealthRecord[] = [
	// Healthy sensors (20)
	{
		sensorId: "s-1",
		lastReportedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-2",
		lastReportedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-3",
		lastReportedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-4",
		lastReportedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-5",
		lastReportedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-6",
		lastReportedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-7",
		lastReportedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-8",
		lastReportedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-9",
		lastReportedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-10",
		lastReportedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-11",
		lastReportedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-12",
		lastReportedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-13",
		lastReportedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-14",
		lastReportedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-15",
		lastReportedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-16",
		lastReportedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-17",
		lastReportedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-18",
		lastReportedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-19",
		lastReportedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	{
		sensorId: "s-20",
		lastReportedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "healthy",
	},
	// Stale sensors (12)
	{
		sensorId: "s-21",
		lastReportedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-22",
		lastReportedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-23",
		lastReportedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-24",
		lastReportedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-25",
		lastReportedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-26",
		lastReportedAt: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-27",
		lastReportedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-28",
		lastReportedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-29",
		lastReportedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-30",
		lastReportedAt: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-31",
		lastReportedAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	{
		sensorId: "s-32",
		lastReportedAt: new Date(Date.now() - 23 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "stale",
	},
	// Silent sensors (8)
	{
		sensorId: "s-33",
		lastReportedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-34",
		lastReportedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-35",
		lastReportedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-36",
		lastReportedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-37",
		lastReportedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-38",
		lastReportedAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-39",
		lastReportedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
	{
		sensorId: "s-40",
		lastReportedAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
		expectedIntervalSeconds: 300,
		warningThresholdSeconds: 600,
		criticalThresholdSeconds: 1800,
		healthStatus: "silent",
	},
];

// Data Quality Records
export const dataQualityRecords: DataQualityRecord[] = [
	// Good quality (20)
	{
		sensorId: "s-1",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-2",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 285,
		missingPoints: 3,
		inconsistentPoints: 0,
		completenessPct: 99,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-3",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-4",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 287,
		missingPoints: 1,
		inconsistentPoints: 0,
		completenessPct: 99.7,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-5",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 286,
		missingPoints: 2,
		inconsistentPoints: 0,
		completenessPct: 99.3,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-6",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-7",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 284,
		missingPoints: 4,
		inconsistentPoints: 0,
		completenessPct: 98.6,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-8",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-9",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 286,
		missingPoints: 2,
		inconsistentPoints: 0,
		completenessPct: 99.3,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-10",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-11",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 287,
		missingPoints: 1,
		inconsistentPoints: 0,
		completenessPct: 99.7,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-12",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-13",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 285,
		missingPoints: 3,
		inconsistentPoints: 0,
		completenessPct: 99,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-14",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-15",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 286,
		missingPoints: 2,
		inconsistentPoints: 0,
		completenessPct: 99.3,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-16",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 287,
		missingPoints: 1,
		inconsistentPoints: 0,
		completenessPct: 99.7,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-17",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-18",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 284,
		missingPoints: 4,
		inconsistentPoints: 0,
		completenessPct: 98.6,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-19",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 288,
		missingPoints: 0,
		inconsistentPoints: 0,
		completenessPct: 100,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	{
		sensorId: "s-20",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 287,
		missingPoints: 1,
		inconsistentPoints: 0,
		completenessPct: 99.7,
		consistencyPct: 100,
		freshnessPct: 100,
		qualityStatus: "good",
	},
	// Missing data (12 - stale sensors)
	{
		sensorId: "s-21",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 250,
		missingPoints: 38,
		inconsistentPoints: 0,
		completenessPct: 86.8,
		consistencyPct: 100,
		freshnessPct: 75,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-22",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 240,
		missingPoints: 48,
		inconsistentPoints: 0,
		completenessPct: 83.3,
		consistencyPct: 100,
		freshnessPct: 70,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-23",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 260,
		missingPoints: 28,
		inconsistentPoints: 0,
		completenessPct: 90.3,
		consistencyPct: 100,
		freshnessPct: 80,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-24",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 245,
		missingPoints: 43,
		inconsistentPoints: 0,
		completenessPct: 85.1,
		consistencyPct: 100,
		freshnessPct: 72,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-25",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 230,
		missingPoints: 58,
		inconsistentPoints: 0,
		completenessPct: 79.9,
		consistencyPct: 100,
		freshnessPct: 65,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-26",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 255,
		missingPoints: 33,
		inconsistentPoints: 0,
		completenessPct: 88.5,
		consistencyPct: 100,
		freshnessPct: 78,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-27",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 235,
		missingPoints: 53,
		inconsistentPoints: 0,
		completenessPct: 81.6,
		consistencyPct: 100,
		freshnessPct: 68,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-28",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 265,
		missingPoints: 23,
		inconsistentPoints: 0,
		completenessPct: 92,
		consistencyPct: 100,
		freshnessPct: 82,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-29",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 220,
		missingPoints: 68,
		inconsistentPoints: 0,
		completenessPct: 76.4,
		consistencyPct: 100,
		freshnessPct: 60,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-30",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 248,
		missingPoints: 40,
		inconsistentPoints: 0,
		completenessPct: 86.1,
		consistencyPct: 100,
		freshnessPct: 74,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-31",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 270,
		missingPoints: 18,
		inconsistentPoints: 0,
		completenessPct: 93.8,
		consistencyPct: 100,
		freshnessPct: 85,
		qualityStatus: "missing",
	},
	{
		sensorId: "s-32",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 232,
		missingPoints: 56,
		inconsistentPoints: 0,
		completenessPct: 80.6,
		consistencyPct: 100,
		freshnessPct: 66,
		qualityStatus: "missing",
	},
	// Inconsistent data (8 - silent sensors)
	{
		sensorId: "s-33",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 180,
		missingPoints: 50,
		inconsistentPoints: 58,
		completenessPct: 62.5,
		consistencyPct: 67.8,
		freshnessPct: 45,
		qualityStatus: "inconsistent",
		notes: "Sudden spikes detected",
	},
	{
		sensorId: "s-34",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 160,
		missingPoints: 60,
		inconsistentPoints: 68,
		completenessPct: 55.6,
		consistencyPct: 57.5,
		freshnessPct: 35,
		qualityStatus: "inconsistent",
		notes: "Invalid readings",
	},
	{
		sensorId: "s-35",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 170,
		missingPoints: 55,
		inconsistentPoints: 63,
		completenessPct: 59,
		consistencyPct: 62.9,
		freshnessPct: 40,
		qualityStatus: "inconsistent",
		notes: "Format errors",
	},
	{
		sensorId: "s-36",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 150,
		missingPoints: 65,
		inconsistentPoints: 73,
		completenessPct: 52.1,
		consistencyPct: 51.3,
		freshnessPct: 30,
		qualityStatus: "inconsistent",
		notes: "Sensor malfunction suspected",
	},
	{
		sensorId: "s-37",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 140,
		missingPoints: 70,
		inconsistentPoints: 78,
		completenessPct: 48.6,
		consistencyPct: 44.3,
		freshnessPct: 25,
		qualityStatus: "inconsistent",
		notes: "Severe data quality issues",
	},
	{
		sensorId: "s-38",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 175,
		missingPoints: 52,
		inconsistentPoints: 61,
		completenessPct: 60.8,
		consistencyPct: 65.1,
		freshnessPct: 42,
		qualityStatus: "inconsistent",
		notes: "Connection intermittent",
	},
	{
		sensorId: "s-39",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 130,
		missingPoints: 75,
		inconsistentPoints: 83,
		completenessPct: 45.1,
		consistencyPct: 36.2,
		freshnessPct: 20,
		qualityStatus: "inconsistent",
		notes: "Critical - needs immediate attention",
	},
	{
		sensorId: "s-40",
		window: "24h",
		expectedPoints: 288,
		receivedPoints: 165,
		missingPoints: 58,
		inconsistentPoints: 65,
		completenessPct: 57.3,
		consistencyPct: 60.6,
		freshnessPct: 38,
		qualityStatus: "inconsistent",
		notes: "Encoding issues",
	},
];

// Ingestion Errors (last 24 hours)
export const ingestionErrors: IngestionError[] = [
	// API Errors
	{
		id: "err-1",
		sensorId: "s-33",
		timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_500",
		message: "Internal server error",
		severity: "alert",
	},
	{
		id: "err-2",
		sensorId: "s-34",
		timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_503",
		message: "Service unavailable",
		severity: "alert",
	},
	{
		id: "err-3",
		sensorId: "s-35",
		timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_404",
		message: "Sensor endpoint not found",
		severity: "warning",
	},
	{
		id: "err-4",
		sensorId: "s-36",
		timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_500",
		message: "Internal server error",
		severity: "alert",
	},
	{
		id: "err-5",
		sensorId: "s-37",
		timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_408",
		message: "Request timeout",
		severity: "warning",
	},
	// CSV Errors
	{
		id: "err-6",
		sensorId: "s-38",
		timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
		source: "csv",
		errorCode: "PARSE_ERROR",
		message: "Invalid date format in row 145",
		severity: "warning",
	},
	{
		id: "err-7",
		sensorId: "s-39",
		timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
		source: "csv",
		errorCode: "SCHEMA_MISMATCH",
		message: "Missing required column: sensor_id",
		severity: "alert",
	},
	{
		id: "err-8",
		sensorId: "s-40",
		timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
		source: "csv",
		errorCode: "VALIDATION_ERROR",
		message: "Value out of range in row 87",
		severity: "warning",
	},
	{
		id: "err-9",
		sensorId: "s-33",
		timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
		source: "csv",
		errorCode: "ENCODING_ERROR",
		message: "Invalid UTF-8 sequence",
		severity: "warning",
	},
	{
		id: "err-10",
		sensorId: "s-37",
		timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
		source: "api",
		errorCode: "HTTP_502",
		message: "Bad gateway",
		severity: "alert",
	},
];

// Helper functions
export function getSensorHealthRecord(sensorId: string): SensorHealthRecord | undefined {
	return sensorHealthRecords.find((r) => r.sensorId === sensorId);
}

export function getDataQualityRecord(
	sensorId: string,
	window: QualityWindow = "24h",
): DataQualityRecord | undefined {
	return dataQualityRecords.find((r) => r.sensorId === sensorId && r.window === window);
}

export function getIngestionErrorsForSensor(
	sensorId: string,
	last24h: boolean = true,
): IngestionError[] {
	const errors = ingestionErrors.filter((e) => e.sensorId === sensorId);
	if (last24h) {
		const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);
		return errors.filter((e) => new Date(e.timestamp) >= cutoff);
	}
	return errors;
}

export function getAllIngestionErrorsLast24h(): IngestionError[] {
	const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);
	return ingestionErrors.filter((e) => new Date(e.timestamp) >= cutoff);
}

export function getAgeInMinutes(lastReportedAt: string): number {
	const now = Date.now();
	const lastReported = new Date(lastReportedAt).getTime();
	return Math.floor((now - lastReported) / (60 * 1000));
}

export function formatAge(ageMinutes: number): string {
	if (ageMinutes < 60) {
		return `${ageMinutes}m`;
	} else if (ageMinutes < 1440) {
		return `${Math.floor(ageMinutes / 60)}h ${ageMinutes % 60}m`;
	} else {
		return `${Math.floor(ageMinutes / 1440)}d`;
	}
}
