import { cleanMessages } from "./i18n/clean";
import { extractMessages } from "./i18n/extract";
import { replaceTranslations } from "./i18n/replace";
import { translateMessages } from "./i18n/translate";

type I18nCommand = "extract" | "replace" | "clean" | "translate";

function printUsage(): void {
	// Single entrypoint contract:
	// 1) This script receives exactly one command argument.
	// 2) The command selects one i18n workflow end-to-end.
	// 3) Any invalid or missing command prints help and exits non-zero.
	console.log("Usage: bun scripts/i18n.ts <extract|replace|clean|translate>");
}

async function run(command: I18nCommand): Promise<void> {
	switch (command) {
		case "extract":
			// EXTRACT FLOW:
			// 1) Read source locale catalog generated by Lingui (`en-US.json`).
			// 2) Build/update `messages.json` using source message text as key.
			// 3) Ensure locale columns exist for all configured locales.
			// 4) Keep existing manual translations intact (merge, not overwrite).
			// 5) Report new and obsolete messages for translator follow-up.
			extractMessages();
			console.log("i18n extraction completed!");
			return;
		case "replace":
			// REPLACE FLOW:
			// 1) Read translation matrix from `messages.json`.
			// 2) Open each locale catalog file (`<locale>.json`).
			// 3) Match entries by source message text.
			// 4) Push translated values into Lingui `translation` fields.
			// 5) Persist locale catalogs and print per-locale update stats.
			replaceTranslations();
			console.log("\ni18n translation replacement completed!");
			return;
		case "clean":
			// CLEAN FLOW:
			// 1) Compare current source catalog messages vs `messages.json` keys.
			// 2) Detect obsolete keys (no longer present in code extraction).
			// 3) Show exactly what will be removed, including existing translations.
			// 4) Ask for explicit confirmation to avoid accidental data loss.
			// 5) Rewrite `messages.json` containing only active source messages.
			await cleanMessages();
			console.log("\ni18n cleanup completed!");
			return;
		case "translate":
			// TRANSLATE FLOW:
			// 1) Read untranslated entries from `messages.json`.
			// 2) Ask target locales and translation confirmation from the user.
			// 3) Call Amazon Translate for each pending source string.
			// 4) Protect placeholders/ICU fragments before and after translation.
			// 5) Save back to `messages.json`, then run `replace` to apply catalogs.
			await translateMessages();
			console.log("\nTranslation completed!");
			return;
	}
}

const command = process.argv[2];
if (!command || !["extract", "replace", "clean", "translate"].includes(command)) {
	printUsage();
	process.exit(1);
}

run(command as I18nCommand).catch((error) => {
	console.error("Error running i18n command:", error instanceof Error ? error.message : error);
	process.exit(1);
});
